name: 'lighthouse-action'
description: 'lighthouse-action'
author: 'seungjaey'

inputs:
  INPUT_URL_PREFIX:
    required: true
    description: 'URL Prefix (ex: http://localhost:3000)'

  INPUT_URL_LIST:
    required: true
    description: 'Test url list'

  INPUT_GH_TOKEN:
    required: false
    description: 'Github Token'

outputs:
  OUTPUT_MD:
    description: 'Lighthouse Report MD Format string'

runs:
  using: 'node16'
  main: 'dist/index.js'
